Hello_Page: Microverse_First_Project_Week_One
Dinma-Faith/Hello-Microverse-Page pull request #1
Opened 2022-02-14 20:06 UTC by Dinma-Faith

-Created HTML and CSS file
-Added Github folder, workflows folder with linters.yml file inside the folders
-Added .gitignore file
-Added test.md in .gitignore file
-Added a README file

2022-02-14 20:14 UTC, Wes-Isaac requested changes
Hi @Dinma-Faith , 

Impressive work so far! 
There are some issues that you still need to work on to go to the next project but you are almost there!

### 📝👌 Your project highlights 🔥😎

- Splendid work with the README file 👀

## Required Changes ♻️

- [ ] Please make sure that linters are checked in the pull request and all linters pass, linters result should be green

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-15 11:06 UTC, elmar8287 approved these changes
Hi @Dinma-Faith, 

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

![](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-15 11:06 UTC, elmar8287 commented on README.md
> +
- [ ] [OPTIONAL] To make your repo more informative, you can add instructions on how to start with your project on the local machine, using the `git clone` command.

2022-02-15 11:06 UTC, elmar8287 commented on index.html
> +    <h1 class="header">"Hello Microverse!"</h1>
- [ ] [OPTIONAL] You can use the text "Hello Microverse" without parentheses 👍

2022-02-15 11:06 UTC, elmar8287 commented on index.html
> +   <!--header-->
- [ ] [OPTIONAL] You can remove comments from your code to make it more clear 👍

2022-02-15 12:40 UTC, merged